import type { Employee, CalendarEvent, Department, Position, User, Role, Site } from './types';

export const employees: Employee[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Lead Software Engineer',
    department: 'Technology',
    email: 'alice.j@staffhub.com',
    phone: '123-456-7890',
    location: 'New York, NY',
    nik: '3201234567890001',
    placeOfBirth: 'Jakarta',
    dateOfBirth: new Date('1990-05-15'),
    address: '123 Main St, Anytown, USA',
    accountNumber: '1234567890',
    bankName: 'Bank Central Asia',
    accountHolderName: 'Alice Johnson',
    maritalStatus: 'married',
    emergencyContactName: 'Bob Johnson',
    emergencyContactNumber: '098-765-4321',
    bpjsStatus: 'active',
    employeeStatus: 'active',
    simPhoto: 'https://placehold.co/600x400.png',
    sioPhoto: 'https://placehold.co/600x400.png',
    simperNumber: 'SIMPER123',
    idCardNumber: 'ID12345',
    messRoomNumber: 'A-101',
    messEntryDate: new Date('2023-01-10'),
    contractStartDate: new Date('2023-01-01'),
    contractEndDate: new Date('2025-01-01'),
    position: 'Lead Software Engineer',
    siteLocation: 'Head Office',
  },
  {
    id: '2',
    name: 'Bob Williams',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Product Manager',
    department: 'Product',
    email: 'bob.w@staffhub.com',
    phone: '123-456-7891',
    location: 'San Francisco, CA',
    employeeStatus: 'active',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'UI/UX Designer',
    department: 'Design',
    email: 'charlie.b@staffhub.com',
    phone: '123-456-7892',
    location: 'Austin, TX',
    employeeStatus: 'active',
  },
  {
    id: '4',
    name: 'Diana Prince',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'HR Specialist',
    department: 'Human Resources',
    email: 'diana.p@staffhub.com',
    phone: '123-456-7893',
    location: 'Chicago, IL',
    employeeStatus: 'nonaktif',
  },
  {
    id: '5',
    name: 'Ethan Hunt',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Marketing Lead',
    department: 'Marketing',
    email: 'ethan.h@staffhub.com',
    phone: '123-456-7894',
    location: 'Miami, FL',
    employeeStatus: 'resign',
  },
  {
    id: '6',
    name: 'Fiona Glenanne',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Frontend Developer',
    department: 'Technology',
    email: 'fiona.g@staffhub.com',
    phone: '123-456-7895',
    location: 'Remote',
    employeeStatus: 'phk',
  },
  {
    id: '7',
    name: 'George Costanza',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Sales Representative',
    department: 'Sales',
    email: 'george.c@staffhub.com',
    phone: '123-456-7896',
    location: 'New York, NY',
    employeeStatus: 'active',
  },
  {
    id: '8',
    name: 'Hannah Abbott',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Data Analyst',
    department: 'Technology',
    email: 'hannah.a@staffhub.com',
    phone: '123-456-7897',
    location: 'San Francisco, CA',
    employeeStatus: 'active',
  },
];

const today = new Date();
export const calendarEvents: CalendarEvent[] = [
    { date: new Date(today.getFullYear(), today.getMonth(), 5), title: "Alice J. - Annual Leave", type: 'leave' },
    { date: new Date(today.getFullYear(), today.getMonth(), 10), title: "Company Wide Town Hall", type: 'event' },
    { date: new Date(today.getFullYear(), today.getMonth(), 11), title: "Company Wide Town Hall", type: 'event' },
    { date: new Date(today.getFullYear(), today.getMonth(), 25), title: "Public Holiday", type: 'holiday' },
    { date: new Date(today.getFullYear(), today.getMonth() + 1, 1), title: "Public Holiday", type: 'holiday' },
    { date: new Date(today.getFullYear(), 0, 1), title: "New Year's Day", type: 'holiday' },
    { date: new Date(today.getFullYear(), 6, 4), title: "Independence Day", type: 'holiday' },
    { date: new Date(today.getFullYear(), 11, 25), title: "Christmas Day", type: 'holiday' },
];

export const departments: Department[] = [
    { id: '1', name: 'Technology' },
    { id: '2', name: 'Product' },
    { id: '3', name: 'Design' },
    { id: '4', name: 'Human Resources' },
    { id: '5', name: 'Marketing' },
    { id: '6', name: 'Sales' },
];

export const positions: Position[] = [
    { id: '1', name: 'Lead Software Engineer' },
    { id: '2', name: 'Product Manager' },
    { id: '3', name: 'UI/UX Designer' },
    { id: '4', name: 'HR Specialist' },
    { id: '5', name: 'Marketing Lead' },
    { id: '6', name: 'Frontend Developer' },
    { id: '7', name: 'Sales Representative' },
    { id: '8', name: 'Data Analyst' },
];

export const users: User[] = [
    { id: '1', name: 'Admin User', email: 'admin@irena.com', role: 'Administrator', password: 'admin' },
    { id: '2', name: 'Admin Proyek 1', email: 'admin.proyek@irena.com', role: 'Admin Proyek', siteId: '1', password: 'adminproyek' },
    { id: '3', name: 'General User', email: 'user@staffhub.com', role: 'Employee', password: 'user' },
];

export const roles: Role[] = [
    { id: '1', name: 'Administrator', description: 'Full access to all features' },
    { id: '2', name: 'HR', description: 'Access to employee management features' },
    { id: '3', name: 'Employee', description: 'Basic access to their own profile' },
    { id: '4', name: 'Admin Proyek', description: 'Project-specific administrative access' },
];


export const sites: Site[] = [
    { id: '1', name: 'Proyek Tambang Kaltim', picId: '1', picName: 'Alice Johnson', picContact: '123-456-7890', supervisors: [{ id: '2', name: 'Bob Williams' }] },
    { id: '2', name: 'Proyek Konstruksi Jakarta', picId: '3', picName: 'Charlie Brown', picContact: '123-456-7892', supervisors: [] },
    { id: '3', name: 'Site Maintenance Surabaya' },
];
