import type { Employee, CalendarEvent } from './types';

export const employees: Employee[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Lead Software Engineer',
    department: 'Technology',
    email: 'alice.j@staffhub.com',
    phone: '123-456-7890',
    location: 'New York, NY',
  },
  {
    id: '2',
    name: 'Bob Williams',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Product Manager',
    department: 'Product',
    email: 'bob.w@staffhub.com',
    phone: '123-456-7891',
    location: 'San Francisco, CA',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'UI/UX Designer',
    department: 'Design',
    email: 'charlie.b@staffhub.com',
    phone: '123-456-7892',
    location: 'Austin, TX',
  },
  {
    id: '4',
    name: 'Diana Prince',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'HR Specialist',
    department: 'Human Resources',
    email: 'diana.p@staffhub.com',
    phone: '123-456-7893',
    location: 'Chicago, IL',
  },
  {
    id: '5',
    name: 'Ethan Hunt',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Marketing Lead',
    department: 'Marketing',
    email: 'ethan.h@staffhub.com',
    phone: '123-456-7894',
    location: 'Miami, FL',
  },
  {
    id: '6',
    name: 'Fiona Glenanne',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Frontend Developer',
    department: 'Technology',
    email: 'fiona.g@staffhub.com',
    phone: '123-456-7895',
    location: 'Remote',
  },
  {
    id: '7',
    name: 'George Costanza',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Sales Representative',
    department: 'Sales',
    email: 'george.c@staffhub.com',
    phone: '123-456-7896',
    location: 'New York, NY',
  },
  {
    id: '8',
    name: 'Hannah Abbott',
    avatar: 'https://placehold.co/100x100/D2E9E6/136F63',
    role: 'Data Analyst',
    department: 'Technology',
    email: 'hannah.a@staffhub.com',
    phone: '123-456-7897',
    location: 'San Francisco, CA',
  },
];

const today = new Date();
export const calendarEvents: CalendarEvent[] = [
    { date: new Date(today.getFullYear(), today.getMonth(), 5), title: "Alice J. - Annual Leave", type: 'leave' },
    { date: new Date(today.getFullYear(), today.getMonth(), 10), title: "Company Wide Town Hall", type: 'event' },
    { date: new Date(today.getFullYear(), today.getMonth(), 11), title: "Company Wide Town Hall", type: 'event' },
    { date: new Date(today.getFullYear(), today.getMonth(), 25), title: "Public Holiday", type: 'holiday' },
    { date: new Date(today.getFullYear(), today.getMonth() + 1, 1), title: "Public Holiday", type: 'holiday' },
    { date: new Date(today.getFullYear(), 0, 1), title: "New Year's Day", type: 'holiday' },
    { date: new Date(today.getFullYear(), 6, 4), title: "Independence Day", type: 'holiday' },
    { date: new Date(today.getFullYear(), 11, 25), title: "Christmas Day", type: 'holiday' },
];
